SOCIAL_PLATFORMS = {
    "Twitter": "https://twitter.com/{}",
    "Instagram": "https://instagram.com/{}",
    "Facebook": "https://facebook.com/{}",
    "GitHub": "https://github.com/{}",
    "Reddit": "https://reddit.com/user/{}",
    "TikTok": "https://www.tiktok.com/@{}",
    "LinkedIn": "https://www.linkedin.com/in/{}",
    "Pinterest": "https://pinterest.com/{}",
    "YouTube": "https://www.youtube.com/@{}",
    "Medium": "https://medium.com/@{}",
    "Snapchat": "https://www.snapchat.com/add/{}",
    "Tumblr": "https://{}.tumblr.com",
    "Vimeo": "https://vimeo.com/{}",
    "SoundCloud": "https://soundcloud.com/{}",
    "DeviantArt": "https://deviantart.com/{}",
    "Twitch": "https://www.twitch.tv/{}",
    "AskFM": "https://ask.fm/{}",
    "Flickr": "https://www.flickr.com/people/{}",
    "Steam": "https://steamcommunity.com/id/{}",
    "GitLab": "https://gitlab.com/{}",
    "Bitbucket": "https://bitbucket.org/{}",
    "Dribbble": "https://dribbble.com/{}",
    "500px": "https://500px.com/{}",
    "Goodreads": "https://www.goodreads.com/{}",
    "VK": "https://vk.com/{}",
    "JackoLive": "https://jacko.live/{}",
    # مواقع الدردشة
    "Telegram": "https://t.me/{}",
    "Discord": "https://discord.com/users/{}",  # عادة يحتاج ID وليس username
    "Skype": "https://join.skype.com/invite/{}",
    "Messenger": "https://m.me/{}",
    "WeChat": "https://www.wechat.com/en/user/{}",  # عام فقط
    "Signal": "https://signal.me/#p/{}",            # غالبًا يحتاج رقم هاتف
    "LINE": "https://line.me/R/ti/p/~{}",
    "Viber": "https://invite.viber.com/?g2={}",     # معرف أو رقم
    "Kik": "https://kik.me/{}",
    "ICQ": "https://icq.im/{}",
    "IRCCloud": "https://www.irccloud.com/#!/user/{}",
    "Tox": "https://tox.chat/{}",
    "Matrix": "https://matrix.to/#/@{}:matrix.org",
    "Slack": "https://{}.slack.com",
    "Clubhouse": "https://www.clubhouse.com/@{}",
    "Zalo": "https://zalo.me/{}",
    "MeetMe": "https://www.meetme.com/{}",
    "Chatango": "https://{}.chatango.com/",
    "Paltalk": "https://www.paltalk.com/people/{}",
    "Sawaksa": "https://sawaksa.com/{}"
}