SOCIAL_PLATFORMS = {
    "Twitter": "https://twitter.com/{}",
    "Instagram": "https://instagram.com/{}",
    "Facebook": "https://facebook.com/{}",
    "GitHub": "https://github.com/{}",
    "Reddit": "https://reddit.com/user/{}",
    "TikTok": "https://www.tiktok.com/@{}",
    "LinkedIn": "https://www.linkedin.com/in/{}",
    "Pinterest": "https://pinterest.com/{}",
    "YouTube": "https://www.youtube.com/@{}",
    "Medium": "https://medium.com/@{}",
    "Snapchat": "https://www.snapchat.com/add/{}",
    "Tumblr": "https://{}.tumblr.com",
    "Vimeo": "https://vimeo.com/{}",
    "SoundCloud": "https://soundcloud.com/{}",
    "DeviantArt": "https://deviantart.com/{}",
    "Twitch": "https://www.twitch.tv/{}",
    "AskFM": "https://ask.fm/{}",
    "Flickr": "https://www.flickr.com/people/{}",
    "Steam": "https://steamcommunity.com/id/{}",
    "GitLab": "https://gitlab.com/{}",
    "Bitbucket": "https://bitbucket.org/{}",
    "Dribbble": "https://dribbble.com/{}",
    "500px": "https://500px.com/{}",
    "Goodreads": "https://www.goodreads.com/{}",
    "VK": "https://vk.com/{}",
    "JackoLive": "https://jacko.live/{}"
}